### ISSUE TITLE
Error in local install instructions

### ISSUE THREAD

**Issue by jaraco** [python3statement/python3statement.github.io#149]
I ran the local install instructions on a macOS 10.13 system with Ruby installed via Homebrew, but got the following error when trying to run the server:

```
python3statement.github.io feature/cherrypy $ jekyll serve -w
Traceback (most recent call last):
        10: from /usr/local/bin/jekyll:23:in `<main>'
         9: from /usr/local/bin/jekyll:23:in `load'
         8: from /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.8.3/exe/jekyll:11:in `<top (required)>'
         7: from /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.8.3/lib/jekyll/plugin_manager.rb:50:in `require_from_bundler'
         6: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/bundler.rb:107:in `setup'
         5: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/bundler/runtime.rb:26:in `setup'
         4: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/bundler/runtime.rb:26:in `map'
         3: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/forwardable.rb:229:in `each'
         2: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/forwardable.rb:229:in `each'
         1: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/bundler/runtime.rb:31:in `block in setup'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/bundler/runtime.rb:313:in `check_for_activated_spec!': You have already activated rouge 3.2.1, but your Gemfile requires rouge 2.2.1. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
```

**Comment by jaraco** [comment]
Seems the recommendation by the error message does work around the issue:

```
python3statement.github.io feature/cherrypy $ bundle exec jekyll serve -w
Configuration file: /Users/jaraco/code/public/python3statement.github.io/_config.yml
            Source: /Users/jaraco/code/public/python3statement.github.io
       Destination: /Users/jaraco/code/public/python3statement.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 2.071 seconds.
 Auto-regeneration: enabled for '/Users/jaraco/code/public/python3statement.github.io'
    Server address: http://0.0.0.0:4000
  Server running... press ctrl-c to stop.
```

**Comment by jaraco** [comment]
Here's the [full install log](https://gist.github.com/346dd11872bdc3ea8e0ded6a4b296d36).

**Comment by Carreau** [comment]
Yeah I always use bundle with jekyll, I think we can update the instruction. 
It is also pre-deployed on netlify so we could actually tell people: send a PR, and click on the preview link if you can't get it to work on your machine.

**Comment by Carreau** [comment]
See #152, I'm not a ruby person, so invocationas are magics to me.

**Comment by avangmbp** [comment]
> ຂ້ອຍແລ່ນຄໍາແນະນໍາການຕິດຕັ້ງທ້ອງຖິ່ນຢູ່ໃນລະບົບ macOS 10.13 ທີ່ມີ Ruby ຕິດຕັ້ງຜ່ານ Homebrew, ແຕ່ໄດ້ຮັບຂໍ້ຜິດພາດຕໍ່ໄປນີ້ເມື່ອພະຍາຍາມແລ່ນ server:
> 
> ```
> python3statement.github.io feature/cherrypy $ jekyll serve -w
> Traceback (most recent call last):
>         10: from /usr/local/bin/jekyll:23:in `<main>'
>          9: from /usr/local/bin/jekyll:23:in `load'
>          8: from /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.8.3/exe/jekyll:11:in `<top (required)>'
>          7: from /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.8.3/lib/jekyll/plugin_manager.rb:50:in `require_from_bundler'
>          6: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/bundler.rb:107:in `setup'
>          5: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/bundler/runtime.rb:26:in `setup'
>          4: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/bundler/runtime.rb:26:in `map'
>          3: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/forwardable.rb:229:in `each'
>          2: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/forwardable.rb:229:in `each'
>          1: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/bundler/runtime.rb:31:in `block in setup'
> /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/bundler/runtime.rb:313:in `check_for_activated_spec!': You have already activated rouge 3.2.1, but your Gemfile requires rouge 2.2.1. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
> ```

https://github.com/python3statement/python3statement.github.io/issues/149#issue-356218560
